### ISSUE TITLE
启动完成后貌似无法登录

### ISSUE THREAD

**Issue by J-Snowwite** [YulinSec/ChatGPTScan-SAST#1]
root@ubuntu23:~/ChatGPTScan-SAST/deploy# docker compose up -d
[+] Running 3/3
 ✔ Container db     Started                                                                                                                                                3.9s 
 ✔ Container web    Started                                                                                                                                                5.1s 
 ✔ Container nginx  Started  

![image](https://user-images.githubusercontent.com/75126343/236158418-82af7257-832f-4437-beea-4fa2fcdbdcee.png)

**Comment by R3col** [comment]
F12 看看Network里有没有接口响应报错的。

**Comment by hydra-0425** [comment]
可以检查你的docker-compose版本是否是最新版本。
如果在Linux系统：

```
VERSION=$(curl --silent https://api.github.com/repos/docker/compose/releases/latest | grep -Po '"tag_name": "\K.*\d')

DESTINATION=/usr/local/bin/docker-compose

sudo curl -L https://github.com/docker/compose/releases/download/${VERSION}/docker-compose-$(uname -s)-$(uname -m) -o $DESTINATION

sudo chmod 755 $DESTINATION
```
最后用以下命令检查版本
```
docker-compose --version
```
![image](https://user-images.githubusercontent.com/132568073/236246311-f78a27a1-4434-400f-921e-67bcf8764ab3.png)

**Comment by J-Snowwite** [comment]
昨天自己排查了下，看看了日志，发现数据库链接失败，因为内存问题，数据库被系统kill了，之后加了内存重新启动就可以了，建议加一个限制，就是承载docker 的虚拟机最好是6G以上，至少我这里6G内存就可以了，但是4G内存就无法使用
